-- Script de carga basica de datos de OSC

-- :%s/;$/;N\/D/

-- %s/\(^.*\);\(.*\)/INSERT INTO t_osc \(`osc_nombre`,`osc_acuerdo`\) VALUES \('\1'\,'\2');/

INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ACDE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ADOPTARE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AEDROS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AMA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ANIDAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ARPA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ARTICULAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASDRA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASOCIACIÓN CIVIL ORY','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASOCIACION MUTUAL SENDEROS (MTE)','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASPERGER','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('BOCA SOCIAL','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CAZADORES DE ARTE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CHICOS NATURALISTAS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CIUDADANOS DEL MUNDO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CREAR CAMINOS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CUENTA CONMIGO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CURAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DONAR SANGRE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EMILIE JENECHERU','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FADEPOF','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FLEXER','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FOC  (Fund.Org.Comunitaria)','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACION DIGNAMENTE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACION MONTESSORI','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACIÓN PARA EL BIENESTAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACION SENDERO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACIÓN VIDA y ESPERANZA (FUNDAVE)','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUPREMUS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GDFE (Grupo de FUndaciones y Empresas)','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GERMINAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HABITAT PARA LA HUMANIDAD ARGENTINA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HOGAR DE SAN JOSE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('IMPULSAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('INCLUBYTE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA USINA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LOS HIJOS DEL CAMPO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MANOS VERDES','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MUSEO DE ARTE MODERNO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PASTORAL SOCIAL','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PIEL','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PROACTIVA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SAGIJ','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SAHDES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SEGUNDA OPORTUNIDAD','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SUR SOLIDARIO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('UNION GITANA UNIVERSAL','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('A.C.I.A.P.O.','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ACEPAR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ADOBE','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ALPI','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ALTERNATIVA 3','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AMARTYA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASHOKA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CANALES','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CASA RAFAEL','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CILSA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Club de amigos mios','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CREAR VALE LA PENA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DONCEL','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EDUCACION PARA COMPARTIR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EQUIDAD','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FAIAM','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUCA - Fundación para la Investigación y la Prevención del Cáncer','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GERMINARE','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GREENPEACE','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('INFANT','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('IONKOS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('L.A.L.C.E.C.','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA NACION D1','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MARIA DE LAS CARCELES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MISSING CHILDREN','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RED DE COMUNIDADES RURALES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SURCOS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('VICAR.EPISC DE EDU DEL ARZ. DE BS.AS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('VIVIENDA DIGNA (SAG FAMILIA)','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AAAEPAD','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ABRIL SOLIDARIO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AMJA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASCINUEN','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASOCIACION ARGENTINA DE KARATE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CAII','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CASA DEL ENCUENTRO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CLUB DEPORTIVO BONGIOVANNI','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DEBRA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DIGNIDAD','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FEPAIS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FRENTE JOVEN','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('JOVENES EN ACCION','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LAS CARITAS DEL TUYU','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MADRE TIERRA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PANZAS LLENAS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PEREGRINA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PILARES','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SILOE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('UNA MANO QUE AYUDA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ACIFAD','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AEPSO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AL REPARO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ALANON','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ALEGRIA INTENSIVA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ALPAD','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ANUAR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ARTESANIAS ARGENTINAS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASOCIACION ARGENTINA DE EDUCADORES SEXUALES','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CRUZ ROJA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CULTIVARTE','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DAR ES DAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FARN -Ambiente y Recursos Naturales','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FLOR','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUND.TODAVIA ES TIEMPO - HOGAR EL ARCA DE NOE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HACIENDO CAMINO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HACIENDO LIO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HAMPATU','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Hecho por Nosotros/Animana','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('IDEL','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA LIGA DE LA LECHE','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LAPDI','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MATERNA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('OBRA DEL PADRE MARIO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PARROQUIA SANTA MARIA DEL CAMINO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PROYECTAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Proyecto Empujar','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RED  DE INNOVACION LOCAL','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SONRISAS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('WENTEMIL','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CAMBIO DEMOCRATICO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CARE','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DAD','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DAMAS ROSADAS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DETODOSPARATODOS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FE Y ALEGRIA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('IDEALISTAS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('INAC','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MANOS ABIERTAS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PALLIUM LATINOAMERICA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PH 15','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RESPONDE','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RUBICOM','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RUGBY SOLIDARIO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EJERCITO DE SALVACION','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ESCLEROSIS MULTIPLE ARGENTINA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA COLIFATA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('NORDELTA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PROYECTOS PADRES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AAPPG','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ALIMENTARIS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('APA (Asoc.Psicoanalitica Argentina)','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ARGENTINA NARRADA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CARITAS NACIONAL','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('COMUNIA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Espacio de Escucha','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EVE (Eduacación en Valores)','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FIORIRE','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACION EVOLUCION','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Fundacion Inter Americana del Corazón - Argentina','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MANOS EN ACCION','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RUGBY SIN FRONTERAS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('TECHO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('VIDA SILVESTRE ARGENTINA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('WINGU','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('YONOFUI','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ADC','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AEDIN','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AMARANTA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASAC Asoc.Ayuda al Ciego','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AVANZAR','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AVES ARGENTINAS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CAMINANDO JUNTOS (UNITED WAY)','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CIENCIA PARA TODOS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CIMIENTOS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CIRCO SOCIAL DEL SUR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CONVIVIR','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('COSIENDO REDES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DE LA NADA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DEFENSORES DEL CHACO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DEHUM','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DESAFIO E IGUALDAD','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DONDE QUIERO ESTAR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EDUCAR Y CRECER','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EL ALMENDRO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EL PUENTE POSIBLE','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ENSEÑA POR ARG.','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ESCUELAS DEL BICENTENARIO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ETIS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FONGA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FORGE','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACION DE TRANSPLANTE HEPATICO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GRANJA ANDAR','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HORIZONTE DE MAXIMA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HUERTA NIÑO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('INTEGRAR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA FLECHA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA REVISTITA MULTICULTURAL','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MADRES DE SAN LORENZO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MARIA DE OS ANGELES','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MATRIARCADO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MICROJUSTICIA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MOVILIZARSE','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('NOSOTROS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('OLIMPIADAS ESPECIALES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PESCAR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PIES DESCALZOS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RED DE BANCO DE ALIMENTOS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SECHI/CIUDAD OCULTA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SECHI/LACARRA-CARRILLO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SOLIDAGRO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('TEMAS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('TREN DEL ALMA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('UNIENDO CAMINOS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MUJERES 2000','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AMERICAN JOINT DISTRIBUTION COMMITTEE','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AMIA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ANDARES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('APAER','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ASOCIACION FILANTROPICA ISRAELITA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('BANCO DE ALIMENTOS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('BASTONES VERDES','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CARLOS DIAZ VELEZ','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CASA DEL TEATRO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('COLEGIO DE ESCRIBANOS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DISCAR','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Don Orione','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ECOCLUBES','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ENABLIS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ENDEAVOR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ESCOLARES','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FORES','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FORO DEL SECTOR SOCIAL','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Fundacion Ronald McDonald','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Fundacion Sistema B','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACION SUMA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GARRAHAN','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HUESPED','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('IELADEINU  (Jabad Lubavitch)','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA SCALA DE SAN TELMO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LEER','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LOS NARANJOS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MUNDO SANO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MUSEO DEL HOLOCAUSTO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('NUTRIR LA VIDA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PELOTA DE TRAPO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PODER CIUDADANO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PROEM -Proyecto Emprender','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RECIDUCA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SES','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SUMA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('TZEDAKA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('U.D.E.S.A.','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('VOCES VITALES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ZAMBRANO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ALMA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ARTE Y ESPERANZA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('BRINCAR','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CASA DEL NIÑO NUEVA FAMILIA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Comprometerse mas','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('COMPROMISO','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CONCIENCIA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CONIN LUJAN','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CREANDO LAZOS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DALE TU MANO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EL ARRANQUE','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EL REPARO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ESCUELA TALLER FATIMA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FANDA   ','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FOVEFOMI','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GRAN CHACO','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GRANO DE MOSTAZA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('GUIDO BUFFO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HELP ARG.','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HERMANAS HOSPITALARIAS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HOGAR MA.DEL ROSARIO DE SAN NICOLAS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HOGAR MARIA LUISA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HOGAR SAGRADA FAMILIA/PILAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HOGAR SANTA RAFAELA MARIA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA BASE','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LAS TUNAS ','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LUCERO DEL ALBA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MEDIA  PILA','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MISIONES RURALES ARGENTINAS','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MUSEO MUJICA LAINEZ','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('OAJNU (org.arg.jov.para nac unidas)','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PAR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PROYECTO DE LUZ','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RAMSEYER','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('RUTA 40','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('STEPS','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('UNIVERSO AGORA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('VALORES PARA CRECER','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('VISITAS ANIMADAS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ACCERVIL','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ADESAR','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AGAPAO','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('AIKEN','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ALDEAS INFANTILES','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Anybody Argentina','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CENTRO THEVENET','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CERO A LA DERECHA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CESUM','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('CHAP','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('COLEGIO MADRE TERESA','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('COOPERATIVA DECAPOLIS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('DIAGONAL','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('EMAUS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('ESPERANZA VIVA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FERIADO AL PLANETA ','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('Fundación Lebensohn','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('FUNDACION MARIA CECILIA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('HOGAR NIÑO JESUS','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LA NUBE','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LEKOTEK','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('LUZ DE ESPERANZA ','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MANOS DE LA CAVA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MENSAJEROS DE LA PAZ','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('MINKAI','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PATA PILA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PROGRESAR','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('PROTEGE TU CORAZON','FIRMADO');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SEMBRAR VALORES','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('SUMANDO ARG.','N/D');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('UASI-LA CAVA','PENDIENTE');
INSERT INTO t_osc (`osc_nombre`,`osc_acuerdo`) VALUES ('VERGEL','PENDIENTE');
