-- 
-- :%s/\(^.*\)\;.\(.*\)/INSERT INTO t_osc_objetivos \(`osc_nombre`,`osc_objetivo`\) VALUES \('\1','\2'\);/
--
\. ./Scr_Ins_datos/que_base_V1.4.sql


INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('COLEGIO DE ESCRIBANOS','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CONVIVIR','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CONVIVIR','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DEHUM','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EL ALMENDRO','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EL REPARO','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EMMANUEL','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FONGA','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PAR','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RUBICOM','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SEGUNDA OPORTUNIDAD','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CERO A LA DERECHA','Comunicacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CERO A LA DERECHA','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('COMUNIA','Comunicacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA FLECHA','Comunicacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA NACION D1','Comunicacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ABRIL SOLIDARIO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ACDE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ACIFAD','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ADC','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ADOPTARE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AIDIS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AIKEN','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALANON','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALANON','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALDEAS INFANTILES','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALDEAS INFANTILES','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALDEAS INFANTILES','Medio Ambiente');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALIMENTARIS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMARTYA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMERICAN JOINT DISTRIBUTION COMMITTEE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMIA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMJA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ANIDAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ANIDAR','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ANUAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Anybody Argentina','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('APAER','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('APAER','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ARTESANIAS ARGENTINAS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASDRA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASDRA','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASOCIACION FILANTROPICA ISRAELITA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASOCIACION MUTUAL SENDEROS (MTE)','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASOCIACION MUTUAL SENDEROS (MTE)','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AVANZAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AVES ARGENTINAS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('BOCA SOCIAL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('BOCA SOCIAL','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CAII','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CAMINANDO JUNTOS (UNITED WAY)','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CARITAS NACIONAL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CASA DEL TEATRO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CAZADORES DE ARTE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CIUDADANOS DEL MUNDO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CLUB DEPORTIVO BONGIOVANNI','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CONCIENCIA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('COOPERATIVA DECAPOLIS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CREANDO LAZOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CREAR CAMINOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CUENTA CONMIGO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CURAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CURAR','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DAD','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DAR ES DAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DAR ES DAR','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DE LA NADA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DEFENSORES DEL CHACO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DESAFIO E IGUALDAD','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DETODOSPARATODOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DIGNIDAD','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Don Orione','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EDUCACION PARA COMPARTIR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EDUCACION PARA COMPARTIR','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EJERCITO DE SALVACION','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EL ARRANQUE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EMAUS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ENABLIS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Espacio de Escucha','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ESPERANZA VIVA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FE Y ALEGRIA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FLOR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FOC  (Fund.Org.Comunitaria)','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FORO DEL SECTOR SOCIAL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FOVEFOMI','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FRENTE JOVEN','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Fundación Lebensohn','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACION SUMA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GRAN CHACO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GUIDO BUFFO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HABITAT PARA LA HUMANIDAD ARGENTINA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HACIENDO CAMINO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HACIENDO LIO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HAMPATU','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Hecho por Nosotros/Animana','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HOGAR DE SAN JOSE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HOGAR DE SAN JOSE','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HOGAR MA.DEL ROSARIO DE SAN NICOLAS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HOGAR SAGRADA FAMILIA/PILAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HOGAR SANTA RAFAELA MARIA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HORIZONTE DE MAXIMA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HUERTA NIÑO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IELADEINU  (Jabad Lubavitch)','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IEM. Un Nuevo Humanismo','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IMPULSAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IONKOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA BASE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LAS TUNAS ','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LOS HIJOS DEL CAMPO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MADRE TIERRA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MADRES DE SAN LORENZO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MANOS ABIERTAS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MANOS DE LA CAVA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MANOS EN ACCION','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MARGARITA BARRIENTOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MARIA DE OS ANGELES','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MENSAJEROS DE LA PAZ','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MICROJUSTICIA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MINKAI','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MUSEO DE ARTE MODERNO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MUSEO DEL HOLOCAUSTO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MUSEO MUJICA LAINEZ','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('NUEVOS CAMINOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('OAJNU (org.arg.jov.para nac unidas)','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('OBRA DEL PADRE MARIO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('OBRA DEL PADRE MARIO','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('OBRA DEL PADRE MARIO','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PANZAS LLENAS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PARROQUIA SANTA MARIA DEL CAMINO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PASTORAL SOCIAL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PATA PILA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PEREZ BUGALLO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PH 15','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PIES DESCALZOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PILARES','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PODER CIUDADANO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PRO VIVIENDA SOCIAL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROGRESAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROTEGE TU CORAZON','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROTEGE TU CORAZON','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROYECTO DE LUZ','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROYECTOS PADRES','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RECIDUCA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RED  DE INNOVACION LOCAL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RED DE COMUNIDADES RURALES','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RESPONDE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RUGBY SIN FRONTERAS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RUTA 40','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RUTA 40','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SECHI/CIUDAD OCULTA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SECHI/LACARRA-CARRILLO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SEMBRAR VALORES','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SILOE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SILOE','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SOLIDAGRO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SONRISAS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SONRISAS','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SONRISAS','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SUR SOLIDARIO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SUR SOLIDARIO','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('TECHO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('TEMAS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('TREN DEL ALMA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('TZEDAKA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('UASI-LA CAVA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('UNA MANO QUE AYUDA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('UNA MANO QUE AYUDA','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('UNIENDO CAMINOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('UNION GITANA UNIVERSAL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('UNIVERSO AGORA','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('VIVIENDA DIGNA (SAG FAMILIA)','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('VOCES VITALES','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ACCERVIL','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AL REPARO','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CARE','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CASCOS VERDES','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CENTRO THEVENET','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Club de amigos mios','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EMPRENDER','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FANDA','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACIÓN PARA EL BIENESTAR','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACIÓN PARA EL BIENESTAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACIÓN PARA EL BIENESTAR','Tercera Edad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GRANJA ANDAR','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IDEL','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IDEL','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('JUNTOS SIN DIFERENCIAS','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA USINA','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('NOSOTROS','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('OLIMPIADAS ESPECIALES','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROACTIVA','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RAMSEYER','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('STEPS','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('STEPS','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('TRIADE','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('WENTEMIL','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ACER /Conin San Isidro','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AEAPG ASOCIACION ESCUELA ARG DE PSICOTERAPIA GRADUADOS','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AEAPG ASOCIACION ESCUELA ARG DE PSICOTERAPIA GRADUADOS','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ARGENTINA NARRADA','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASHOKA','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASOCIACION ARGENTINA DE EDUCADORES SEXUALES','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CARLOS DIAZ VELEZ','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CASA DEL NIÑO NUEVA FAMILIA','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CASA RAFAEL','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CASA RAFAEL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CHICOS NATURALISTAS','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CIMIENTOS','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('COLEGIO MADRE TERESA','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Comprometerse mas','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Comprometerse mas','Adicciones');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DALE TU MANO','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DALE TU MANO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EDUCAR Y CRECER','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ENDEAVOR','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ENSEÑA POR ARG.','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ESCOLARES','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ESCUELAS DEL BICENTENARIO','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ETIS','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EVE (Eduacación en Valores)','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FEPAIS','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FORGE','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACION MONTESSORI','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GERMINARE','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GRANO DE MOSTAZA','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('INTEGRAR','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('JOVENES EN ACCION','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LEER','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LEKOTEK','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MEDIA  PILA','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MEDIA  PILA','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MISIONES RURALES ARGENTINAS','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Orientacion a la Joven','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PESCAR','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROYECTAR','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROYECTAR','Medio Ambiente');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Proyecto Empujar','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PUENTES','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RUGBY SOLIDARIO','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SOCIEDAD DAMAS DE LA MISERICORDIA','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('VALORES PARA CRECER','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('VISITAS ANIMADAS','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AEDROS','Fortalecimiento');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GDFE (Grupo de FUndaciones y Empresas)','Fortalecimiento');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IMPULSAR','Fortalecimiento');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SUMANDO ARG.','Fortalecimiento');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SUMANDO ARG.','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALEGRIA INTENSIVA','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMARANTA','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMARANTA','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AMARANTA','Tercera Edad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CONIN LUJAN','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CONIN LUJAN','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CULTIVARTE','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CULTIVARTE','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DONCEL','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DONCEL','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EMILIE JENECHERU','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUND.TODAVIA ES TIEMPO - HOGAR EL ARCA DE NOE','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUND.TODAVIA ES TIEMPO - HOGAR EL ARCA DE NOE','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUND.TODAVIA ES TIEMPO - HOGAR EL ARCA DE NOE','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACION DIGNAMENTE','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Fundacion Ronald McDonald','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Fundacion Ronald McDonald','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACIÓN VIDA y ESPERANZA (FUNDAVE)','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HOGAR MARIA LUISA','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HOGAR NIÑO JESUS','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA NUBE','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA NUBE','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LAS LOMAS ORAL','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LAS LOMAS ORAL','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('VERGEL','Infancia');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('INCLUBYTE','Informatica');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('INCLUBYTE','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('INCLUBYTE','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('WINGU','Informatica');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ADOBE','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AEDIN','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ARTE Y ESPERANZA','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASAC Asoc.Ayuda al Ciego','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASAC Asoc.Ayuda al Ciego','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASOCIACION ARGENTINA DE KARATE','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CANALES','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CASA DEL ENCUENTRO','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CASA NIÑO MARIA DE NAZARETH','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CILSA','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DIAGONAL','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DISCAR','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EL PUENTE POSIBLE','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('EQUIDAD','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACION EVOLUCION','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACION EVOLUCION','Educacion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GARRAHAN','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HELP ARG.','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA COLIFATA','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA REVISTITA MULTICULTURAL','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LOS NARANJOS','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LOS NARANJOS','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MARIA DE LAS CARCELES','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PELOTA DE TRAPO','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PEREGRINA','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROEM -Proyecto Emprender','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PROEM -Proyecto Emprender','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('YONOFUI','Integracion');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FARN -Ambiente y Recursos Naturales','Medio Ambiente');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GERMINAR','Medio Ambiente');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GERMINAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MANOS VERDES','Medio Ambiente');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('VIDA SILVESTRE ARGENTINA','Medio Ambiente');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('A.C.I.A.P.O.','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AAAEPAD','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AAPPG','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ADESAR','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ADESAR','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AEPSO','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AGAPAO','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AGAPAO','Comunidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALMA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALPI','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('APA (Asoc.Psicoanalitica Argentina)','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ARPA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ARTICULAR','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASCINUEN','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASPERGER','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASPERGER','Discapacidad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('BASTONES VERDES','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('BASTONES VERDES','Tercera Edad');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('BRINCAR','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CESUM','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CHAP','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CRUZ ROJA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DAMAS ROSADAS','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DEBRA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DONAR SANGRE','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('DONDE QUIERO ESTAR','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ESCLEROSIS MULTIPLE ARGENTINA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FADEPOF','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FAGRAN ( Federación de Nutricionistas)','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FIORIRE','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FLEXER','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACION DE TRANSPLANTE HEPATICO','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Fundacion Inter Americana del Corazón - Argentina','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACION MARIA CECILIA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDALC','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUPREMUS','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HERMANAS HOSPITALARIAS','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('HUESPED','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('INAC','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('INFANT','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('L.A.L.C.E.C.','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LAPDI','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LAS CARITAS DEL TUYU','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MATERNA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MUNDO SANO','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('NUTRIR LA VIDA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PALLIUM LATINOAMERICA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('PIEL','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SAGIJ','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SAHDES','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SUMA','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SURCOS','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ZAMBRANO','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ABRIR LA PUERTA','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ACEPAR','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALPAD','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ALTERNATIVA 3','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ANDARES','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ASOCIACIÓN CIVIL ORY','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('AVINA','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('BANCO DE ALIMENTOS','Alimentos');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CAMBIO DEMOCRATICO','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CIENCIA PARA TODOS','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CIRCO SOCIAL DEL SUR','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('COMPROMISO','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('COSIENDO REDES','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('CREAR VALE LA PENA','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ECOCLUBES','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('ESCUELA TALLER FATIMA','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FAIAM','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FERIADO AL PLANETA ','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FORES','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUCA - Fundación para la Investigación y la Prevención del Cáncer','Salud');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('FUNDACION SENDERO','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('Fundacion Sistema B','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('GREENPEACE','Medio Ambiente');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IDEALISTAS','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('IPA','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA LIGA DE LA LECHE','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LA SCALA DE SAN TELMO','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LUCERO DEL ALBA','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('LUZ DE ESPERANZA ','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MATRIARCADO','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MI HUERTA','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MIRADAS DE AMOR','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MISSING CHILDREN','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MOVILIZARSE','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('MUJERES 2000','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('NORDELTA','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('RED DE BANCO DE ALIMENTOS','Alimentos');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('SES','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('U.D.E.S.A.','No Especificado');
INSERT INTO t_osc_objetivos (`osc_nombre`,`osc_objetivo`) VALUES ('VICAR.EPISC DE EDU DEL ARZ. DE BS.AS','No Especificado');
