
-- :%s/\(^.*\);\(.*\)/INSERT INTO t_osc_logs_dc \(`osc_nombre`,`dni`,`osc_rol_dc`\)  VALUES \('\1'\,'\2','Suplente');/

\. ./Scr_Ins_datos/que_base_V1.4.sql


INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ADESAR','1000206','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('GREENPEACE','1000206','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SILOE','1000206','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SONRISAS','1000206','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('TEMAS','1000206','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('VIDA SILVESTRE ARGENTINA','1000206','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CARITAS NACIONAL','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('COMPROMISO','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CONVIVIR','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('DISCAR','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('FARN -Ambiente y Recursos Naturales','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('HUESPED','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('IMPULSAR','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('LA COLIFATA','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PUENTES','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('UNIENDO CAMINOS','1000202','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('DIAGONAL','1000205','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('Fundación Lebensohn','1000205','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('HACIENDO CAMINO','1000205','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MUSEO DE ARTE MODERNO','1000205','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SUR SOLIDARIO','1000205','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ASDRA','1000207','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CAII','1000207','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('FIORIRE','1000207','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('HORIZONTE DE MAXIMA','1000207','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MENSAJEROS DE LA PAZ','1000207','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PROYECTO DE LUZ','1000207','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('VIVIENDA DIGNA (SAG FAMILIA)','1000207','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('A.C.I.A.P.O.','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('AEDIN','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ALIMENTARIS','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ALPI','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ASAC Asoc.Ayuda al Ciego','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('BOCA SOCIAL','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CREAR VALE LA PENA','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('DE LA NADA','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ETIS','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('FORES','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('HUERTA NIÑO','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('LA NACION D1','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MARIA DE OS ANGELES','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PAR','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PASTORAL SOCIAL','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PELOTA DE TRAPO','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PODER CIUDADANO','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SECHI/CIUDAD OCULTA','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SECHI/LACARRA-CARRILLO','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SES','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('UNIVERSO AGORA','1000201','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ALDEAS INFANTILES','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('AMIA','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('AVES ARGENTINAS','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ENDEAVOR','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('FLEXER','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('Fundacion Ronald McDonald','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('GARRAHAN','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('LA NUBE','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PESCAR','1000203','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('AEAPG ASOCIACION ESCUELA ARG DE PSICOTERAPIA GRADUADOS','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('AVANZAR','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CASA RAFAEL','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('COLEGIO DE ESCRIBANOS','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('DEFENSORES DEL CHACO','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ECOCLUBES','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('GRANJA ANDAR','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('Hecho por Nosotros/Animana','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MADRE TIERRA','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MINKAI','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MUNDO SANO','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MUSEO DEL HOLOCAUSTO','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MUSEO MUJICA LAINEZ','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('YONOFUI','1000200','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ADOBE','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ANDARES','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('BANCO DE ALIMENTOS','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CLUB DEPORTIVO BONGIOVANNI','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('Don Orione','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('EL ARRANQUE','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('EMMANUEL','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('FERIADO AL PLANETA ','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('FORO DEL SECTOR SOCIAL','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('HOGAR SAGRADA FAMILIA/PILAR','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('LUZ DE ESPERANZA ','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MISIONES RURALES ARGENTINAS','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('NUEVOS CAMINOS','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PILARES','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SURCOS','13394776','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CAMINANDO JUNTOS (UNITED WAY)','12332887','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('Club de amigos mios','12332887','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('FORGE','12332887','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('FUNDALC','12332887','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ACDE','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('AEDROS','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('AMJA','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CIMIENTOS','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CONCIENCIA','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ESCUELAS DEL BICENTENARIO','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('GDFE (Grupo de FUndaciones y Empresas)','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('GERMINARE','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('GRAN CHACO','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('IMPULSAR','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('INFANT','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('LAS TUNAS ','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MEDIA  PILA','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('NORDELTA','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('NOSOTROS','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('Proyecto Empujar','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PROYECTOS PADRES','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('RED DE BANCO DE ALIMENTOS','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SOLIDAGRO','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('UNA MANO QUE AYUDA','1000204','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ACER /Conin San Isidro','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ADC','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('AMARTYA','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ASHOKA','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CARLOS DIAZ VELEZ','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CILSA','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CRUZ ROJA','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('DAD','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('DEBRA','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('DONCEL','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('EDUCACION PARA COMPARTIR','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('EL ALMENDRO','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('ESCLEROSIS MULTIPLE ARGENTINA','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('Fundacion Sistema B','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('IONKOS','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('L.A.L.C.E.C.','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MOVILIZARSE','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('OLIMPIADAS ESPECIALES','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PIES DESCALZOS','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('RESPONDE','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('SOCIEDAD DAMAS DE LA MISERICORDIA','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('TECHO','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('VOCES VITALES','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('WINGU','93609657','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('APAER','14772995','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('CASA DEL TEATRO','14772995','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('DEHUM','14772995','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('EDUCAR Y CRECER','14772995','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('Espacio de Escucha','14772995','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('MANOS EN ACCION','14772995','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('OBRA DEL PADRE MARIO','14772995','Suplente');
INSERT INTO t_osc_logs_dc (`osc_nombre`,`dni`,`osc_rol_dc`) VALUES ('PEREGRINA','14772995','Suplente');

-- UPDATE `t_osc_logs_dc` SET `osc_comentarios_dc`= "Carga inicial de DC Suplente" WHERE osc_rol_dc = "Suplente";
